name: Update Metrics Picture

on:
  workflow_dispatch:

jobs:
  update-metrics-picture:
    name: Update Metrics Picture
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_aliases: "JavaScript:JS"
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%
          plugin_languages_limit: 8
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 7
          commits_authoring: github-actions@github.com
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
